name: Deploy Images to GHCR

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Push Docker image to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GIT_TOKEN}}

      - name: Set Docker image name
        id: set-image-name
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build . -f Dockerfile --tag ghcr.io/pierredurrr/${{ env.IMAGE_NAME }}:latest

      - name: Push the Docker image
        id: push-docker-image
        run: docker push ghcr.io/pierredurrr/${{ env.IMAGE_NAME }}:latest 
