name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        id: docker-hub
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo $password | docker login -u $username --password-stdin

      - name: Set Docker image name
        id: set-image-name
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Build the Docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build . -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Push the Docker image
        id: push-docker-image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
